name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ opened, labeled, master ]
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Change directory ownership
      run: sudo chown -R $(whoami) $ANDROID_HOME
    - name: Build with Gradle
      run: sudo ./gradlew build --stacktrace
    - name: Android Github Action
      uses: Vukan-Markovic/Github-Android-Action@1.2


  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to To Project
    steps:
    - name: Assign NEW issues and NEW pull requests to CHILD project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/elirehema/arcolios/projects/2'

    - name: Assign issues and pull requests with `enhancement` label to CHILD project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'enhancement') ||
        contains(github.event.pull_request.labels.*.name, 'enhancement')
      with:
        project: 'https://github.com/elirehema/arcolios/projects/2'
        column_name: 'To do'
    - name: Assign NEW issues and NEW pull requests to HEADER project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/users/elirehema/projects/3'

    - name: Assign issues and pull requests with `enhancement` label to HEADER project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'enhancement') ||
        contains(github.event.pull_request.labels.*.name, 'enhancement')
      with:
        project: 'https://github.com/users/elirehema/projects/3'
        column_name: 'To do' 

